server:
  port: 8000
  
spring:
  application:
    name: zipkinServer
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 0.5
  sample:
    zipkin:
      enabled: true