server:
  port: 7000

spring:
  application:
    name: zipkinClient
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 0.5
  sample:
    zipkin:
      enabled: true